"""CS 1430 - Assignment 1 self-check.

Run this file. It checks your toolchain and your work, then writes
SUBMISSION.txt for you to upload in Canvas.

You do not need to install anything to run this. Do not edit this file.
"""
import ast
import hashlib
import subprocess
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).parent
MAIN = HERE / "main.py"
SUBMISSION = HERE / "SUBMISSION.txt"

TOP_MARK = "DO NOT EDIT BELOW THIS LINE"
BOTTOM_MARK = "DO NOT EDIT ABOVE THIS LINE"

# Filled in when this template was built. Do not change these.
BANNER_FINGERPRINT = "bae6d77d119e143e"
TEMPLATE_PRINTS = 2
TEMPLATE_OUTPUT_LINES = 10

BAR = "=" * 70
results = []


def record(ok, label, detail="", hint=""):
    results.append((ok, label, detail, hint))


def git(*args):
    """Run a git command in this folder. Returns (returncode, stdout)."""
    try:
        done = subprocess.run(
            ["git", *args], cwd=HERE,
            capture_output=True, text=True, timeout=25,
        )
        return done.returncode, done.stdout.strip()
    except FileNotFoundError:
        return 127, ""
    except subprocess.TimeoutExpired:
        return 124, ""


def tidy(text):
    """Line endings and trailing spaces do not count as changing the art."""
    body = text.replace("\r\n", "\n").replace("\r", "\n")
    return "\n".join(line.rstrip() for line in body.split("\n")).strip()


def fingerprint(text):
    return hashlib.sha256(tidy(text).encode("utf-8")).hexdigest()[:16]


def protected_block(source):
    """The text between the two DO NOT EDIT markers, or None if they are gone."""
    start = source.find(TOP_MARK)
    end = source.find(BOTTOM_MARK)
    if start == -1 or end == -1 or end < start:
        return None
    return source[source.find("\n", start) + 1:source.rfind("\n", 0, end)]


def count_prints(source):
    """How many print(...) calls are in this file. None if it will not parse."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None
    return sum(
        1 for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "print"
    )


# --------------------------------------------------------------------------
# Your toolchain
# --------------------------------------------------------------------------
v = sys.version_info
record(True, "Python is installed", f"{v.major}.{v.minor}.{v.micro}")

record(MAIN.exists(), "main.py is in this folder", "",
       "Open the FOLDER you cloned in VS Code, not just a single file.")

source = MAIN.read_text(encoding="utf-8") if MAIN.exists() else ""

program_output = ""
ran = False
if MAIN.exists():
    done = subprocess.run([sys.executable, str(MAIN)],
                          capture_output=True, text=True)
    ran = done.returncode == 0
    program_output = done.stdout.rstrip()
    error_text = done.stderr
    tail = error_text.strip().splitlines()
    error_tail = tail[-1] if tail else ""
else:
    error_text = ""
    error_tail = ""

run_hint = "Run main.py on its own and read the LAST line of the red text."
if not ran and "\\" in source:
    run_hint = ('If your ASCII art contains \\ characters, put the letter r '
                'right before your opening quotes, like this:  MY_NAME = r"""')
record(ran, "main.py runs without an error", error_tail, run_hint)

# --------------------------------------------------------------------------
# Your work
# --------------------------------------------------------------------------
block = protected_block(source)
if block is None:
    record(False, "The ASCII art is unchanged", "",
           "The DO NOT EDIT lines are missing. Copy main.py from the "
           "template repository and start over, keeping your own print lines.")
else:
    record(fingerprint(block) == BANNER_FINGERPRINT,
           "The ASCII art is unchanged", "",
           "Something between the DO NOT EDIT lines was changed. Copy that "
           "section back from the template repository on GitHub.")

prints = count_prints(source)
if prints is None:
    record(False, "You added at least one print statement", "",
           "main.py has a typo Python cannot read. Fix the error above first.")
else:
    record(prints > TEMPLATE_PRINTS,
           "You added at least one print statement",
           f"{prints - TEMPLATE_PRINTS} added",
           "Add a print() below the ADD YOUR CODE line with your name in it.")

new_lines = max(0, len([l for l in program_output.splitlines() if l.strip()])
                - TEMPLATE_OUTPUT_LINES)
plural = "" if new_lines == 1 else "s"
record(new_lines > 0, "Your name shows up when the program runs",
       f"{new_lines} new line{plural} of output",
       "Fix the error above first." if not ran else
       "Your print ran but printed nothing. Put your name inside the "
       "quotation marks.")

# --------------------------------------------------------------------------
# Git and GitHub
# --------------------------------------------------------------------------
code, version = git("--version")
record(code == 0, "Git is installed", version,
       "Git did not run. Revisit the Git install step, then close and "
       "reopen VS Code.")

code, _ = git("rev-parse", "--is-inside-work-tree")
record(code == 0, "This folder is a Git repository", "",
       "You may have downloaded the files instead of cloning your repo.")

code, message = git("log", "-1", "--pretty=%s")
record(code == 0 and bool(message), "You have made a commit",
       f'"{message}"' if message else "",
       "Stage your change, write a commit message, and commit it.")

_, author = git("log", "-1", "--pretty=%an")

code, url = git("remote", "get-url", "origin")
url = url.replace(".git", "")
linked = code == 0 and "github.com" in url
record(linked, "This repo points at GitHub",
       url.replace("https://", "") if linked else "",
       "There is no 'origin' remote. Did you clone from YOUR repository?")

local_sha = git("rev-parse", "HEAD")[1]
code, listing = git("ls-remote", "origin", "HEAD")
remote_sha = listing.split()[0] if code == 0 and listing else ""
if not linked:
    pushed_hint = "Fix the line above first -- this repo has no GitHub address."
elif not remote_sha:
    pushed_hint = ("Could not reach GitHub. Check your internet connection, "
                   "then run this file again.")
else:
    pushed_hint = ("Committing saves your work on this computer. PUSH sends it "
                   "to GitHub. Push now, then run this file again.")
record(bool(remote_sha) and remote_sha == local_sha,
       "Your commit is pushed to GitHub", local_sha[:7], pushed_hint)

# --------------------------------------------------------------------------
# Report
# --------------------------------------------------------------------------
passed = all(ok for ok, *_ in results)
user = url.split("github.com/")[-1].split("/")[0] if linked else ""
stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

lines = [BAR, " CS 1430  -  ASSIGNMENT 1 SELF CHECK", f" {stamp}   {author}", BAR]
for ok, label, detail, hint in results:
    lines.append(f" [{'PASS' if ok else 'FAIL'}] {label:<42} {detail}")
    if not ok and hint:
        lines.append(f"        -> {hint}")
lines.append(BAR)

report = "\n".join(lines)
print(report)

if passed:
    print(" ALL CHECKS PASSED.")
    print(f" SUBMISSION.txt has been written to this folder.")
    print(" Upload that file in Canvas, then answer the reflection questions.")
else:
    print(" Not finished yet. Fix the FIRST line that says FAIL,")
    print(" then run this file again.")
print(BAR)

if ran and "invalid escape sequence" in error_text:
    print(" NOTE: Python printed a warning about the \\ characters in your art.")
    print(" Your program still works. To clear the warning, put the letter r")
    print(' just before your opening quotes:   MY_NAME = r"""')
    print(BAR)

SUBMISSION.write_text("\n".join([
    BAR,
    " CS 1430  -  ASSIGNMENT 1  -  SUBMISSION RECEIPT",
    BAR,
    " Status         : " + ("COMPLETE - all checks passed"
                            if passed else "INCOMPLETE - see failures below"),
    f" GitHub user    : {user}",
    f" Repository     : {url}",
    f" Commit         : {local_sha[:7]}  {message}",
    f" Commit author  : {author}",
    f" Generated      : {stamp}",
    "",
    " SELF CHECK",
    report,
    "",
    " WHAT YOUR PROGRAM PRINTED",
    BAR,
    program_output,
    BAR,
    "",
]), encoding="utf-8")
